name: 'Lint PR title'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config:
            rules:
              body-leading-blank:
              - 1
              - always
              body-max-line-length:
              - 2
              - always
              - 120
              footer-leading-blank:
              - 1
              - always
              footer-max-line-length:
              - 2
              - always
              - 120
              header-max-length:
              - 2
              - always
              - 120
              references-empty:
              - 1
              - never
              scope-case:
              - 2
              - always
              - lower-case
              subject-empty:
              - 2
              - never
              subject-full-stop:
              - 2
              - never
              - "."
              type-case:
              - 2
              - always
              - lower-case
              type-empty:
              - 2
              - never
              type-enum:
              - 2
              - always
              - - build
                - ci
                - chore
                - docs
                - feat
                - fix
                - perf
                - infra
                - refactor
                - revert
                - style
                - test
            parserPreset:
              parserOpts:
                referenceActions: 
                issuePrefixesCaseSensitive: true
                issuePrefixes:
                - ADATA-
                - CONTENT-
                - OSINSPIRE-
                - MINT-
                - OSACCNT-
                - PWAC-
                - SAB-
                - WTF-
                - XCCWS-
            